[features]
seeds = false
skip-lint = false
[programs.localnet]
multi_send = "CYtTx9XGqxEJSjxXvNz2ZYgC2J8brQGL5vj6uAi1ukQr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/namvu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
